[package]
name = "gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[features]
voice = ["dep:voice"]

[dependencies]
anyhow.workspace = true
auto_update.workspace = true
gpui = { git = "https://github.com/zed-industries/zed", default-features = false }
gpui-component = { git = "https://github.com/longbridge/gpui-component", default-features = false }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = [
    "font-kit",
] }
image = { version = "0.25", default-features = false, features = ["png"] }
notify-rust = { version = "4", default-features = false }
release_channel.workspace = true
semver.workspace = true
settings.workspace = true
sound.workspace = true
tracing.workspace = true
tray-icon = { version = "0.24", default-features = false, features = ["gtk", "libxdo"] }
voice = { workspace = true, optional = true }

[lints]
workspace = true
