[package]
name = "gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[features]
voice = ["dep:voice"]

[dependencies]
anyhow.workspace = true
auto_update.workspace = true
gpui-fps = { version = "0.6", default-features = false }
gpui-kit = { git = "https://github.com/longbridge/gpui-kit", rev = "9504b4658d57c59024a664f22b5ab55e070a24b4", default-features = false, features = [
    "component",
] }
gpui-pre = { version = "0.3", default-features = false, features = [
    "profiler",
] }
gpui_thinking_orbs.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
notify-rust = { version = "4", default-features = false }
release_channel.workspace = true
semver.workspace = true
settings.workspace = true
sound.workspace = true
tracing.workspace = true
tray-icon = { version = "0.25", default-features = false, features = [
    "libappindicator",
    "muda-libxdo",
] }
voice = { workspace = true, optional = true }

[lints]
workspace = true
