[package]
name = "audio_engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = []
gpu = ["dep:wgpu", "dep:pollster"]

[dependencies]
anyhow.workspace = true
memmap2 = { version = "0.9", default-features = false }
pollster = { version = "1", default-features = false, optional = true }
rayon = { version = "1", default-features = false }
tracing.workspace = true
wgpu = { version = "30", default-features = false, features = [
    "dx12",
    "metal",
    "vulkan",
    "gles",
    "wgsl",
], optional = true }

[dev-dependencies]
cpal = { version = "0.18", default-features = false }
criterion = { version = "0.8", default-features = false }
hound = { version = "3.5", default-features = false }

[target.'cfg(windows)'.dev-dependencies]
wasapi = { version = "0.24" }

[target.'cfg(target_os = "linux")'.dev-dependencies]
libpulse-binding = { version = "2.30" }
libpulse-simple-binding = { version = "2.29" }

[target.'cfg(target_os = "macos")'.dev-dependencies]
screencapturekit = { version = "8", features = ["macos_13_0"] }

[[bench]]
name = "bench_gemm"
harness = false

[[bench]]
name = "bench_ops"
harness = false

[lints]
workspace = true
