[package]
name = "audio_engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = []
gpu = ["dep:wgpu", "dep:pollster"]

[dependencies]
anyhow.workspace = true
matrixmultiply = { version = "0.3", default-features = false, features = [
    "avx512",
    "threading",
] }
memmap2 = { version = "0.9", default-features = false }
pollster = { version = "0.4", default-features = false, optional = true }
rayon = { version = "1", default-features = false }
tracing.workspace = true
wgpu = { version = "30", default-features = false, features = [
    "dx12",
    "metal",
    "vulkan",
    "gles",
    "wgsl",
], optional = true }

[dev-dependencies]
cpal = { version = "0.18", default-features = false }
hound = { version = "3.5", default-features = false }
tracing-subscriber.workspace = true

[lints]
workspace = true
