[package]
name = "auto_update"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
path = "src/auto_update.rs"
doctest = false

[dependencies]
anyhow.workspace = true
futures-util = { version = "0.3", default-features = false }
release_channel.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile = { version = "3", default-features = false, features = ["getrandom"] }

[lints]
workspace = true
