[package]
name = "utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
dunce = { version = "1", default-features = false }
globset = { version = "0.4", default-features = false }
itertools = "0.15"
ref-cast = { version = "1", default-features = false }
regex = { version = "1.12", default-features = false }
serde.workspace = true

[lints]
workspace = true
