[alias]
nt = "nextest run --all-features --all-targets --status-level fail --no-fail-fast"

[env]
# Fix incorrect bindings generation with Cranelift on Windows:
# https://aws.github.io/aws-lc-rs/resources.html#bindings-generation
AWS_LC_SYS_NO_U1_BINDINGS = "1"

[build]
incremental = true
rustflags = [
    "--cfg=tokio_unstable",
    "-Ctarget-cpu=native",
    "-Zcache-proc-macros",
    "-Zshare-generics=y",
    "-Zthreads=0",
    "-Znext-solver=globally",
    # "-Zlocation-detail=none",
]

# Fix linking error with Cranelift and `-Clink-arg=-fuse-ld=lld` on Windows
# (pulp 0.22.3)
[profile.dev.package.pulp]
codegen-backend = "llvm"

[unstable]
# build-std = ["std", "panic_abort"]
# build-std-features = ["optimize_for_size"]
checksum-freshness = true
codegen-backend = true
feature-unification = true
profile-hint-mostly-unused = true

[resolver]
feature-unification = "workspace"

[profile.dev]
codegen-backend = "cranelift"

[target.'cfg(target_os = "windows")']
rustflags = [
    "--cfg=windows_slim_errors",
    "--cfg=tokio_unstable",
    "-Ctarget-cpu=native",
    "-Clink-arg=-fuse-ld=lld",
    "-Zcache-proc-macros",
    "-Zshare-generics=y",
    "-Zthreads=0",
    "-Znext-solver=globally",
    # "-Zlocation-detail=none",
]

[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = [
    "--cfg=tokio_unstable",
    "-Clink-arg=-fuse-ld=/usr/bin/mold",
    "-Ctarget-cpu=native",
    "-Zcache-proc-macros",
    "-Zshare-generics=y",
    "-Zthreads=0",
    "-Znext-solver=globally",
    # "-Zlocation-detail=none",
]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "--cfg=tokio_unstable",
    "-Clink-arg=-fuse-ld=/usr/bin/mold",
    "-Ctarget-cpu=native",
    "-Zcache-proc-macros",
    "-Zshare-generics=y",
    "-Zthreads=0",
    "-Znext-solver=globally",
    "-Crelocation-model=static",
    # "-Zlocation-detail=none",
]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-Ctarget-feature=+sign-ext,+nontrapping-fptoint",
]
