[package]
name = "tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
auto_update.workspace = true
paths.workspace = true
ratatui.workspace = true
release_channel.workspace = true
semver.workspace = true
settings.workspace = true
sound.workspace = true
voice.workspace = true

[lints]
workspace = true
