[package]
name = "settings"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
paths.workspace = true
ratatui.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with = { version = "3.22", default-features = false, features = [
    "std",
    "macros",
] }
tracing.workspace = true

[lints]
workspace = true
