[package]
name = "server"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde_json.workspace = true
settings.workspace = true
tokio.workspace = true
tower = { version = "0.5", default-features = false }
tower-http.workspace = true
tracing.workspace = true

[lints]
workspace = true
