[package]
name = "voice"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cpal = { version = "0.18", default-features = false }
matrixmultiply = { version = "0.3", features = ["threading"] }
paths.workspace = true
rayon = "1"
reqwest.workspace = true
tracing.workspace = true

[dev-dependencies]
hound = "3.5"

[lints]
workspace = true
