[package]
name = "voice"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = []
gpu = ["audio_engine/gpu"]

[dependencies]
anyhow.workspace = true
audio_engine.workspace = true
cpal = { version = "0.18", default-features = false }
paths.workspace = true
reqwest.workspace = true
tracing.workspace = true

[lints]
workspace = true
