name: CI

on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy, rustfmt, rustc-codegen-cranelift-preview
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Install mold
      run: |
        sudo apt-get update
        sudo apt-get install -y mold
    - name: Check
      run: cargo clippy --workspace --all-targets --all-features
    - name: rustfmt
      run: cargo fmt --all --check

  check-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustc-codegen-cranelift-preview
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Install mold
      run: |
        sudo apt-get update
        sudo apt-get install -y mold
    - name: cargo doc
      run: cargo doc --all-features --no-deps
    env:
      RUSTDOCFLAGS: "-D rustdoc::all -A rustdoc::private-doc-tests"

  test-versions:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustc-codegen-cranelift-preview
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Install mold
      run: |
        sudo apt-get update
        sudo apt-get install -y mold
    - name: Run tests
      run: cargo nt

  # (04.10.2025) Note: Doctests are currently not supported because of
  # limitations in stable Rust. For now, run doctests in a separate step with
  # cargo test --doc.
  # Source: https://nexte.st/#quick-start
  test-docs:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustc-codegen-cranelift-preview
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Install mold
      run: |
        sudo apt-get update
        sudo apt-get install -y mold
    - name: Run doc tests
      run: cargo test --all-features --doc

  deny-check:
    name: cargo-deny check
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    steps:
      - uses: actions/checkout@v5
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check ${{ matrix.checks }}
          manifest-path: Cargo.toml

  dependencies-are-sorted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install cargo-sort
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-sort
    - name: Check dependency tables
      run: cargo sort --workspace --grouped --check

  typos:
    name: Spellcheck with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Spellcheck repository
        uses: crate-ci/typos@v1.37.2
    env:
      CLICOLOR: 1
